<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <!--        <ApplicationIcon>Assets\.ico</ApplicationIcon>-->
        <AssemblyName>Antigen</AssemblyName>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>$(DefineConstants);ENABLE_XAML_HOT_RELOAD</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Condition="$(DefineConstants.Contains(ENABLE_XAML_HOT_RELOAD))" Include="Avalonia.Markup.Xaml.Loader"/>
        <PackageReference Include="HotAvalonia" Condition="$(DefineConstants.Contains(ENABLE_XAML_HOT_RELOAD))" PrivateAssets="All" Publish="True"/>
        <PackageReference Include="Autofac"/>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Controls.DataGrid"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport"/>
        <PackageReference Include="Deadpikle.AvaloniaProgressRing"/>
        <PackageReference Include="FluentAvaloniaUI"/>
        <PackageReference Include="Microsoft.Extensions.Logging"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Extensions.Logging"/>
        <PackageReference Include="Serilog.Sinks.File"/>
        <PackageReference Include="Mutagen.Bethesda.Analyzers"/>
        <PackageReference Include="Mutagen.Bethesda.Analyzers.Skyrim"/>
        <PackageReference Include="Mutagen.Bethesda.Autofac"/>
        <PackageReference Include="Noggog.UI"/>
        <PackageReference Include="Noggog.UI.Avalonia"/>
        <PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator"/>
        <PackageReference Include="ReactiveUI.Avalonia"/>
        <PackageReference Include="ReactiveUI.SourceGenerators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Sortable.Avalonia"/>
        <PackageReference Include="System.Interactive.Async"/>
        <PackageReference Include="TreeDataGrid.Avalonia"/>
        <PackageReference Include="Xaml.Behaviors.Interactivity"/>
    </ItemGroup>

</Project>
